swagger: "2.0"
info:
  title: Invoice App API Service
  description: RESTFUL API Backend for Invoicify. An open source invoicing web app.
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/v1/create-account:
    post:
      tags:
      - invoice
      summary: CreateAccount invoice
      description: Create an account by email address and password.
      operationId: invoice#CreateAccount
      parameters:
      - name: CreateAccountRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/InvoiceCreateAccountRequestBody'
          required:
          - email
          - name
          - password
      responses:
        "201":
          description: Created response.
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountBadrequestResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountNotfoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/InvoiceCreateAccountServererrorResponseBody'
      schemes:
      - http
  /api/v1/openapi.json:
    get:
      tags:
      - invoice
      summary: Download ./gen/http/openapi.json
      operationId: invoice#/api/v1/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /api/v1/tokens:
    post:
      tags:
      - invoice
      summary: GrantToken invoice
      description: Create an account by email address and password.
      operationId: invoice#GrantToken
      parameters:
      - name: grant_type
        in: query
        required: false
        type: string
        default: access_token
        enum:
        - access_token
        - refresh_token
      - name: GrantTokenRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/InvoiceGrantTokenRequestBody'
          required:
          - email
          - password
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/InvoiceGrantTokenResponseBody'
            required:
            - accessToken
            - refreshToken
            - accessExpiryTime
            - refreshExpiryTime
            - accessExpiryTimeStamp
            - refreshExpiryTimeStamp
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/InvoiceGrantTokenBadrequestResponseBody'
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/InvoiceGrantTokenUnauthorizedResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/InvoiceGrantTokenNotfoundResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/InvoiceGrantTokenServererrorResponseBody'
      schemes:
      - http
definitions:
  InvoiceCreateAccountBadrequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: CreateAccount_badrequest_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceCreateAccountNotfoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: CreateAccount_notfound_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceCreateAccountRequestBody:
    title: InvoiceCreateAccountRequestBody
    type: object
    properties:
      email:
        type: string
        description: Email address of the user
        example: Nemo assumenda aperiam natus ullam ex pariatur.
      id:
        type: string
        description: ID of the user
        example: Alias cumque.
      name:
        type: string
        description: Full name of the user
        example: Deserunt et at ipsum eveniet autem.
      password:
        type: string
        description: Password of the user. This is never returned to the client.
        example: Eaque quam quidem dolorem libero velit.
    example:
      email: Vel ut quia est deleniti quae aut.
      id: Vero molestiae eius.
      name: Tempore eius exercitationem in.
      password: Accusamus quasi.
    required:
    - email
    - name
    - password
  InvoiceCreateAccountServererrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: CreateAccount_servererror_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceCreateAccountUnauthorizedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: CreateAccount_unauthorized_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceGrantTokenBadrequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: GrantToken_badrequest_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceGrantTokenNotfoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: GrantToken_notfound_Response_Body result type (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceGrantTokenRequestBody:
    title: InvoiceGrantTokenRequestBody
    type: object
    properties:
      email:
        type: string
        description: User email
        example: Illo officia voluptates ex quod.
      password:
        type: string
        description: User password
        example: Laudantium libero.
    example:
      email: Occaecati voluptas molestiae nobis facere.
      password: Quia assumenda qui sint sapiente ipsum qui.
    required:
    - email
    - password
  InvoiceGrantTokenResponseBody:
    title: InvoiceGrantTokenResponseBody
    type: object
    properties:
      accessExpiryTime:
        type: integer
        example: 7843115956462264338
        format: int64
      accessExpiryTimeStamp:
        type: string
        example: Esse repellendus.
      accessToken:
        type: string
        example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
      refreshExpiryTime:
        type: integer
        example: 1334392219278916415
        format: int64
      refreshExpiryTimeStamp:
        type: string
        example: Reiciendis magni et et qui.
      refreshToken:
        type: string
        example: Sunt totam temporibus quibusdam quasi autem possimus.
    example:
      accessExpiryTime: 2118452547822873798
      accessExpiryTimeStamp: Atque nisi rem aut.
      accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
      refreshExpiryTime: 6941582188916535944
      refreshExpiryTimeStamp: Fugit iste nihil ex ea placeat iusto.
      refreshToken: Ut veniam voluptatum repellendus et aperiam nesciunt.
    required:
    - accessToken
    - refreshToken
    - accessExpiryTime
    - refreshExpiryTime
    - accessExpiryTimeStamp
    - refreshExpiryTimeStamp
  InvoiceGrantTokenServererrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: GrantToken_servererror_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  InvoiceGrantTokenUnauthorizedResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: GrantToken_unauthorized_Response_Body result type (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
