openapi: 3.0.3
info:
  title: Invoice App API Service
  description: RESTFUL API Backend for Invoicify. An open source invoicing web app.
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /api/v1/create-account:
    post:
      tags:
      - invoice
      summary: CreateAccount invoice
      description: Create an account by email address and password.
      operationId: invoice#CreateAccount
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequestBody'
            example:
              email: Et ut.
              id: Aut quod deserunt voluptas libero et quas.
              name: Et quaerat quasi maxime nam est fugiat.
              password: Sequi et dolore.
      responses:
        "201":
          description: Created response.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/openapi.json:
    get:
      tags:
      - invoice
      summary: Download ./gen/http/openapi.json
      operationId: invoice#/api/v1/openapi.json
      responses:
        "200":
          description: File downloaded
  /api/v1/tokens:
    post:
      tags:
      - invoice
      summary: GrantToken invoice
      description: Create an account by email address and password.
      operationId: invoice#GrantToken
      parameters:
      - name: grant_type
        in: query
        allowEmptyValue: true
        schema:
          type: string
          default: access_token
          example: refresh_token
          enum:
          - access_token
          - refresh_token
        example: access_token
      - name: __Host-token
        in: cookie
        allowEmptyValue: true
        schema:
          type: string
          example: Iure sed iusto sunt.
        example: Et a ut dolorem sit inventore ex.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrantTokenRequestBody'
            example:
              email: Laborum facilis libero.
              password: Eligendi quis.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
              example:
                accessExpiryTime: 3396026838057048242
                accessExpiryTimeStamp: Nam velit architecto illum voluptas odio fuga.
                accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
                refreshExpiryTime: 6932486574096537476
                refreshExpiryTimeStamp: Perspiciatis voluptas.
                refreshToken: Earum voluptatem architecto ea et.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    CreateAccountRequestBody:
      type: object
      properties:
        email:
          type: string
          description: Email address of the user
          example: Quibusdam tenetur occaecati ipsa nihil illum ipsam.
        id:
          type: string
          description: ID of the user
          example: Repellat doloremque distinctio architecto animi.
        name:
          type: string
          description: Full name of the user
          example: Ipsa non enim culpa nobis quia aliquam.
        password:
          type: string
          description: Password of the user. This is never returned to the client.
          example: Aut et.
      example:
        email: Vel consequatur.
        id: Facere doloribus veritatis minima eum beatae.
        name: Aliquid voluptates magni vero.
        password: Culpa at voluptatum ipsa dolor ea.
      required:
      - email
      - name
      - password
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    GrantTokenRequestBody:
      type: object
      properties:
        email:
          type: string
          description: User email
          example: Et nihil libero ut laboriosam.
        password:
          type: string
          description: User password
          example: Temporibus eveniet.
      example:
        email: Ipsum facilis est similique aut id.
        password: Et delectus.
      required:
      - email
      - password
    Token:
      type: object
      properties:
        accessExpiryTime:
          type: integer
          example: 5161384593605469415
          format: int64
        accessExpiryTimeStamp:
          type: string
          example: Architecto doloribus quo.
        accessToken:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
        refreshExpiryTime:
          type: integer
          example: 6403530218774722998
          format: int64
        refreshExpiryTimeStamp:
          type: string
          example: Dignissimos repudiandae fuga est at et perferendis.
        refreshToken:
          type: string
          example: Sit eaque.
      example:
        accessExpiryTime: 8502745685529276309
        accessExpiryTimeStamp: Sunt facilis labore.
        accessToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzaWQiOiJkYmViMjlhYTMyYjg0MTMxYTA0NjY4MDAyNzAxNWEwZSIsInJvbGUiOlsiQWRtaW5pc3RyYXRvcnMiLCJSZWdpc3RlcmVkIFVzZXJzIiwiU3Vic2NyaWJlcnMiXSwiaXNzIjoidGVzdHNpdGVjZS5sdmgubWUiLCJleHAiOjE0NTA4MzU2ODMsIm5iZiI6MTQ1MDgzMTc4M30.Yf3mmBJ8nV_IozqvvLc8L34dDklU2J7z0uXn3jsICp0
        refreshExpiryTime: 4186051162188568620
        refreshExpiryTimeStamp: Voluptas repellat totam in.
        refreshToken: Beatae nam odio ipsam est.
      required:
      - accessToken
      - refreshToken
      - accessExpiryTime
      - refreshExpiryTime
      - accessExpiryTimeStamp
      - refreshExpiryTimeStamp
tags:
- name: invoice
  description: RESTFUL API Backend for Invoicify. An open source invoicing web app.
