openapi: 3.0.3
info:
  title: Invoice App API Service
  description: REST API for the invoice app.
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /create-account:
    post:
      tags:
      - invoice
      summary: create-account invoice
      operationId: invoice#create-account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequestBody'
            example:
              email: Ut odio neque nesciunt.
              id: Illo itaque eveniet non rerum et.
              name: Quisquam vel.
              password: Consectetur esse officiis voluptatum ea nihil fugit.
      responses:
        "201":
          description: Created response.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
  /create-account/{userID}:
    get:
      tags:
      - invoice
      summary: get-account invoice
      operationId: invoice#get-account
      parameters:
      - name: userID
        in: path
        required: true
        schema:
          type: string
          example: Officia voluptates ex quod adipisci laudantium.
        example: Placeat occaecati voluptas molestiae nobis facere.
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAccountRequestBody'
              example:
                email: Deserunt voluptas libero.
                id: Aut molestiae vel autem aut.
                name: Quas nulla et ut hic.
                password: Quaerat quasi maxime nam est.
        "400":
          description: 'badrequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: 'unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: 'notfound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
        "500":
          description: 'servererror: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
  /openapi.json:
    get:
      tags:
      - invoice
      summary: Download ./gen/http/openapi.json
      operationId: invoice#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    CreateAccountRequestBody:
      type: object
      properties:
        email:
          type: string
          example: Nisi rem.
        id:
          type: string
          example: Aperiam nesciunt tempora praesentium aperiam.
        name:
          type: string
          example: Laborum fugit.
        password:
          type: string
          example: Nihil ex.
      example:
        email: Dolore molestias.
        id: Placeat iusto culpa labore aut corporis.
        name: Officia expedita repellat velit neque illum voluptatem.
        password: Officiis eius id quod quae possimus.
      required:
      - email
      - name
      - password
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: false
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
tags:
- name: invoice
  description: REST API for the invoice app.
