// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: blocks.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const insertBlock = `-- name: InsertBlock :exec
INSERT INTO blocks (id, name, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?)
`

type InsertBlockParams struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

func (q *Queries) InsertBlock(ctx context.Context, arg InsertBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertBlock,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
