// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package sqlc

import (
	"database/sql"
	"time"
)

type Config struct {
	ID        string
	Entry     string
	Value     string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Scope struct {
	ID          string
	Name        string
	IsImmutable int32
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type TransientToken struct {
	ID         string
	UserID     string
	Hash       string
	TtlSeconds int32
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type User struct {
	ID         string
	Name       string
	Email      sql.NullString
	PassHash   string
	IsActive   int32
	LoggedInAt sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type UserScope struct {
	ID        string
	UserID    string
	ScopeID   string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
